// This file will be auto-generated by running:
// npx supabase gen types typescript --project-id <your-project-id> > lib/supabase/types.ts
//
// For now, we export the Database type placeholder that all Supabase clients reference.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];
